-- Generated by scripts/gen-seed-sql.ts — do not edit by hand.
insert into public.teams (id, name, short, color, color2, motto, founded, chair_name, chair_since, chair_quote, coach_name) values
  ('f8', 'F8 Warriors', 'F8', '#ff3b5c', '#7a0f24', 'Không lùi bước, máu lửa từ phút đầu tiên', 2024, 'Nguyễn Thanh Sơn', '2024', 'Chơi hết mình, thắng bằng tinh thần.', 'Phạm Đức Hùng'),
  ('f9', 'F9 Titans', 'F9', '#2f8cff', '#0b2a66', 'Kỷ luật tạo nên chiến thắng', 2024, 'Lê Quang Vinh', '2024', 'Mỗi trận là một bài test hệ thống.', 'Trần Minh Đạo');

insert into public.players (id, team_id, name, pos, ovr, num, age, foot, stats) values
  ('p0', 'f8', 'Trần Đức Anh', 'GK', 81, 1, 29, 'Phải', '{86,83,72,85,56,78}'),
  ('p1', 'f8', 'Lê Hoàng Nam', 'CB', 79, 4, 31, 'Trái', '{73,52,69,68,82,79}'),
  ('p2', 'f8', 'Phạm Quốc Bảo', 'CB', 76, 5, 27, 'Phải', '{74,48,68,64,82,83}'),
  ('p3', 'f8', 'Vũ Thành Long', 'LB', 74, 3, 25, 'Phải', '{68,45,69,68,82,79}'),
  ('p4', 'f8', 'Đỗ Minh Khoa', 'CDM', 80, 6, 30, 'Phải', '{73,74,82,85,62,75}'),
  ('p5', 'f8', 'Nguyễn Hữu Phúc', 'CM', 83, 8, 28, 'Phải', '{80,76,88,87,68,77}'),
  ('p6', 'f8', 'Bùi Gia Huy', 'CAM', 87, 10, 26, 'Phải', '{80,87,94,89,74,79}'),
  ('p7', 'f8', 'Hoàng Anh Tú', 'RW', 78, 7, 24, 'Phải', '{81,85,70,77,37,76}'),
  ('p8', 'f8', 'Đặng Văn Quyết', 'ST', 91, 9, 27, 'Trái', '{91,97,86,97,44,87}'),
  ('p9', 'f8', 'Ngô Tiến Dũng', 'LW', 72, 11, 23, 'Phải', '{76,76,70,76,28,67}'),
  ('p10', 'f8', 'Lâm Chí Thanh', 'CM', 68, 14, 35, 'Phải', '{62,63,70,71,57,62}'),
  ('p20', 'f9', 'Phan Văn Hậu', 'GK', 83, 1, 32, 'Trái', '{85,85,68,86,58,85}'),
  ('p21', 'f9', 'Trịnh Quang Hải', 'CB', 82, 4, 29, 'Phải', '{80,55,74,70,86,88}'),
  ('p22', 'f9', 'Lý Công Minh', 'CB', 75, 2, 26, 'Phải', '{69,47,69,61,81,79}'),
  ('p23', 'f9', 'Mai Xuân Trường', 'RB', 73, 12, 24, 'Trái', '{63,44,62,66,81,76}'),
  ('p24', 'f9', 'Dương Thế Vinh', 'CDM', 78, 6, 28, 'Phải', '{75,72,82,82,61,70}'),
  ('p25', 'f9', 'Cao Đức Thắng', 'CM', 85, 8, 27, 'Phải', '{79,78,92,88,70,84}'),
  ('p26', 'f9', 'Hồ Tấn Tài', 'CAM', 80, 10, 25, 'Phải', '{78,80,81,81,68,78}'),
  ('p27', 'f9', 'Tô Hoàng Lâm', 'LW', 77, 11, 23, 'Trái', '{77,84,71,75,36,72}'),
  ('p28', 'f9', 'Lương Công Phượng', 'ST', 89, 9, 30, 'Phải', '{93,95,86,94,42,83}'),
  ('p29', 'f9', 'Kiều Nhật Minh', 'RW', 84, 7, 26, 'Phải', '{84,88,76,87,40,76}'),
  ('p30', 'f9', 'Võ Đình Khôi', 'ST', 66, 19, 22, 'Trái', '{70,69,60,67,24,57}');

insert into public.matches (id, kickoff, home_team, away_team, home_score, away_score, status, venue, scorers) values
  ('m0', '2026-01-10T18:00:00+07:00', 'f8', 'f9', 3, 2, 'done', 'Sân bóng Hoàng Mai · Sân số 3', '[{"pid":"p4","side":"home","min":18},{"pid":"p28","side":"away","min":29},{"pid":"p6","side":"home","min":36},{"pid":"p7","side":"home","min":40},{"pid":"p23","side":"away","min":61}]'),
  ('m1', '2026-02-07T18:00:00+07:00', 'f9', 'f8', 1, 1, 'done', 'Sân bóng Hoàng Mai · Sân số 3', '[{"pid":"p28","side":"home","min":34},{"pid":"p8","side":"away","min":63}]'),
  ('m2', '2026-03-07T18:00:00+07:00', 'f8', 'f9', 0, 2, 'done', 'Sân bóng Hoàng Mai · Sân số 3', '[{"pid":"p30","side":"away","min":28},{"pid":"p27","side":"away","min":41}]'),
  ('m3', '2026-04-04T18:00:00+07:00', 'f9', 'f8', 4, 3, 'done', 'Sân bóng Hoàng Mai · Sân số 3', '[{"pid":"p25","side":"home","min":5},{"pid":"p7","side":"away","min":16},{"pid":"p24","side":"home","min":18},{"pid":"p25","side":"home","min":22},{"pid":"p1","side":"away","min":26},{"pid":"p27","side":"home","min":28},{"pid":"p5","side":"away","min":52}]'),
  ('m4', '2026-05-09T18:30:00+07:00', 'f8', 'f9', 2, 1, 'done', 'Sân bóng Hoàng Mai · Sân số 3', '[{"pid":"p6","side":"home","min":16},{"pid":"p29","side":"away","min":25},{"pid":"p8","side":"home","min":63}]'),
  ('m5', '2026-06-06T18:30:00+07:00', 'f9', 'f8', 2, 2, 'done', 'Sân bóng Hoàng Mai · Sân số 3', '[{"pid":"p28","side":"home","min":10},{"pid":"p4","side":"away","min":23},{"pid":"p3","side":"away","min":36},{"pid":"p27","side":"home","min":40}]'),
  ('m6', '2026-07-11T18:30:00+07:00', 'f8', 'f9', 3, 1, 'done', 'Sân bóng Hoàng Mai · Sân số 3', '[{"pid":"p9","side":"home","min":4},{"pid":"p3","side":"home","min":18},{"pid":"p27","side":"away","min":18},{"pid":"p6","side":"home","min":20}]'),
  ('m7', '2026-08-08T18:30:00+07:00', 'f9', 'f8', 1, 2, 'done', 'Sân bóng Hoàng Mai · Sân số 3', '[{"pid":"p8","side":"away","min":18},{"pid":"p8","side":"away","min":63},{"pid":"p24","side":"home","min":66}]'),
  ('m8', '2026-09-12T18:30:00+07:00', 'f8', 'f9', 1, 3, 'done', 'Sân bóng Hoàng Mai · Sân số 3', '[{"pid":"p24","side":"away","min":15},{"pid":"p26","side":"away","min":40},{"pid":"p25","side":"away","min":48},{"pid":"p6","side":"home","min":60}]'),
  ('m9', '2026-10-03T19:30:00+07:00', 'f9', 'f8', 0, 0, 'up', 'Sân bóng Hoàng Mai · Sân số 3', '[]');

insert into public.transfers (player_id, player_name, from_team, to_team, fee, created_on) values
  ('p10', 'Lâm Chí Thanh', 'f9', 'f8', 1.2, '2026-06-20'),
  ('p30', 'Võ Đình Khôi', 'f8', 'f9', 0.8, '2026-08-01');
