// Prints supabase/seed.sql from the demo league in src/data/seed.ts.
// Usage: npm run gen:seed
// Demo offers need auth users, so scripts/create-users.ts inserts those.
import { seedData } from '../src/data/seed';

const q = (v: unknown): string => {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number') return String(v);
  if (Array.isArray(v)) return `'{${v.join(',')}}'`;
  return `'${String(v).replace(/'/g, "''")}'`;
};
const rows = (xs: unknown[][]) => xs.map((r) => `  (${r.map(q).join(', ')})`).join(',\n');

const d = seedData();
const out = [
  '-- Generated by scripts/gen-seed-sql.ts — do not edit by hand.',
  'insert into public.teams (id, name, short, color, color2, motto, founded, chair_name, chair_since, chair_quote, coach_name) values',
  rows(d.teams.map((t) => [t.id, t.name, t.short, t.color, t.color2, t.motto, t.founded, t.chair.name, t.chair.since, t.chair.quote, t.coach.name])) + ';',
  '',
  'insert into public.players (id, team_id, name, pos, ovr, num, age, foot, stats) values',
  rows(d.players.map((p) => [p.id, p.teamId, p.name, p.pos, p.ovr, p.num, p.age, p.foot, p.stats])) + ';',
  '',
  'insert into public.matches (id, kickoff, home_team, away_team, home_score, away_score, status, venue, scorers) values',
  rows(d.matches.map((m) => [m.id, m.date, m.home, m.away, m.hs, m.as, m.status, m.venue, JSON.stringify(m.scorers)])) + ';',
  '',
  'insert into public.transfers (player_id, player_name, from_team, to_team, fee, created_on) values',
  rows(d.transfers.map((t) => [t.pid, t.name, t.from, t.to, t.fee, t.date])) + ';',
  '',
];
process.stdout.write(out.join('\n'));
