-- In-app notifications, generated by the database:
--   * a new match → players of both teams (+ free agents, + the teams' staff): "bấm Tham gia"
--   * a new tournament → every approved member
--   * XP / stat changes → one notification per match (or per bonus), updated as XP keeps coming in
--   * team application accepted / rejected → the applicant

create table if not exists public.notifications (
  id          bigint generated always as identity primary key,
  user_id     uuid not null references public.profiles on delete cascade,
  kind        text not null,                  -- match | tournament | xp | application
  ref         text not null,                  -- de-dupe key per user, e.g. "match:<id>", "xp:<match id>"
  title       text not null,
  body        text,
  link        text,                           -- hash route, e.g. "#/match/<id>"
  meta        jsonb not null default '{}',
  created_at  timestamptz not null default now(),
  read_at     timestamptz,
  unique (user_id, ref)
);
create index if not exists notifications_user_idx on public.notifications (user_id, created_at desc);

alter table public.notifications enable row level security;
drop policy if exists "notifications: own read" on public.notifications;
create policy "notifications: own read" on public.notifications for select to authenticated using (user_id = auth.uid());
revoke insert, update, delete on public.notifications from anon, authenticated;

create or replace function public.vn_when(t timestamptz) returns text
language sql stable as $$
  select (array['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'])[extract(dow from t at time zone 'Asia/Ho_Chi_Minh')::int + 1]
    || ' ' || to_char(t at time zone 'Asia/Ho_Chi_Minh', 'DD/MM · HH24:MI')
$$;

create or replace function public.mark_notifications_read(p_ids bigint[] default null) returns void
language sql security definer set search_path = public as $$
  update public.notifications set read_at = now()
  where user_id = auth.uid() and read_at is null and (p_ids is null or id = any(p_ids))
$$;
revoke execute on function public.mark_notifications_read(bigint[]) from public, anon;
grant execute on function public.mark_notifications_read(bigint[]) to authenticated;

-- ───────── new match ─────────
create or replace function public.notify_new_match() returns trigger
language plpgsql security definer set search_path = public as $$
declare h text; a text;
begin
  if new.status <> 'up' then return new; end if;
  select short into h from public.teams where id = new.home_team;
  select short into a from public.teams where id = new.away_team;
  insert into public.notifications (user_id, kind, ref, title, body, link)
  select distinct u.id, 'match', 'match:' || new.id,
    '⚽ Trận mới: ' || h || ' vs ' || a,
    public.vn_when(new.kickoff) || ' · ' || new.venue || ' — bấm “Tham gia” để điểm danh (+20 XP)',
    '#/match/' || new.id
  from public.profiles u
  where u.role <> 'pending' and (
    exists (select 1 from public.players p where p.user_id = u.id and (p.team_id in (new.home_team, new.away_team) or p.team_id is null))
    or (u.role in ('chair', 'coach') and u.team_id in (new.home_team, new.away_team)))
  on conflict (user_id, ref) do nothing;
  return new;
end $$;
drop trigger if exists on_match_notify on public.matches;
create trigger on_match_notify after insert on public.matches for each row execute function public.notify_new_match();

-- ───────── new tournament ─────────
create or replace function public.notify_new_tournament() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.notifications (user_id, kind, ref, title, body, link)
  select u.id, 'tournament', 'tour:' || new.id,
    '🏆 Giải đấu mới: ' || new.name,
    case new.format when 's5' then 'Sân 5' else 'Sân 7' end
      || coalesce(' · khai mạc ' || to_char(new.starts_on, 'DD/MM'), '')
      || case when u.role = 'chair' then ' — Chủ tịch bấm “Đăng ký tham gia” trên banner.' else ' — xem thể lệ và giải thưởng.' end,
    '#/tournament/' || new.id
  from public.profiles u where u.role <> 'pending'
  on conflict (user_id, ref) do nothing;
  return new;
end $$;
drop trigger if exists on_tournament_notify on public.tournaments;
create trigger on_tournament_notify after insert on public.tournaments for each row execute function public.notify_new_tournament();

-- ───────── application decided ─────────
create or replace function public.notify_application() returns trigger
language plpgsql security definer set search_path = public as $$
declare u uuid; t text;
begin
  if new.status not in ('accepted', 'rejected') or old.status = new.status then return new; end if;
  select user_id into u from public.players where id = new.player_id;
  if u is null then return new; end if;
  select name into t from public.teams where id = new.team_id;
  insert into public.notifications (user_id, kind, ref, title, body, link)
  values (u, 'application', 'app:' || new.id,
    case when new.status = 'accepted' then '🎉 ' || t || ' đã nhận bạn vào đội!' else '📭 ' || t || ' chưa nhận đơn của bạn' end,
    case when new.status = 'accepted' then 'Chào mừng gia nhập. Xem đội hình và trận tới nhé.' else 'Đừng nản, thử ứng tuyển đội khác hoặc chờ lời mời.' end,
    '#/teams/' || new.team_id)
  on conflict (user_id, ref) do update set title = excluded.title, body = excluded.body, created_at = now(), read_at = null;
  return new;
end $$;
drop trigger if exists on_application_notify on public.team_applications;
create trigger on_application_notify after update of status on public.team_applications for each row execute function public.notify_application();

-- ───────── XP / stats ─────────
-- grant_xp now also reports stats that went up, into one notification per match (or per bonus).
create or replace function public.grant_xp(p_player text, p_match text, p_kind text, p_dist int[], p_note text, p_by uuid default null)
returns boolean
language plpgsql security definer set search_path = public as $$
declare
  total int := (select coalesce(sum(x), 0) from unnest(p_dist) x)::int;
  before int[]; after int[]; pl public.players;
  ups jsonb := '[]'; i int; lbl text[]; eid bigint;
  mt public.matches; h text; a text; v_title text; v_ref text;
begin
  if total = 0 then return false; end if;
  insert into public.player_xp (player_id, match_id, kind, amount, dist, note, created_by)
  values (p_player, p_match, p_kind, total, p_dist, p_note, p_by)
  on conflict do nothing
  returning id into eid;
  if eid is null then return false; end if;
  select stats into before from public.players where id = p_player;
  perform public.apply_xp(p_player, p_dist);
  select * into pl from public.players where id = p_player;
  after := pl.stats;
  if pl.user_id is null then return true; end if;

  lbl := case when pl.pos = 'GK' then array['DIV', 'HAN', 'KIC', 'REF', 'SPD', 'POS'] else array['PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY'] end;
  for i in 1..6 loop
    if after[i] > before[i] then ups := ups || to_jsonb(lbl[i] || ' ' || before[i] || '→' || after[i]); end if;
  end loop;

  if p_match is not null then
    select * into mt from public.matches where id = p_match;
    select short into h from public.teams where id = mt.home_team;
    select short into a from public.teams where id = mt.away_team;
    v_ref := 'xp:' || p_match;
    v_title := 'Kinh nghiệm trận ' || h || ' ' || mt.home_score || '–' || mt.away_score || ' ' || a;
  else
    v_ref := 'xp:' || p_kind || ':' || eid;
    v_title := case when p_kind = 'bonus' then '🧧 Chủ tịch thưởng nóng cho bạn' else 'Kinh nghiệm' end;
  end if;

  insert into public.notifications (user_id, kind, ref, title, link, meta)
  values (pl.user_id, 'xp', v_ref, v_title, case when p_match is not null then '#/match/' || p_match end,
    jsonb_build_object('xp', total, 'notes', jsonb_build_array(p_note), 'ups', ups))
  on conflict (user_id, ref) do update set
    meta = jsonb_build_object(
      'xp', coalesce((public.notifications.meta ->> 'xp')::int, 0) + total,
      'notes', coalesce(public.notifications.meta -> 'notes', '[]') || jsonb_build_array(p_note),
      'ups', coalesce(public.notifications.meta -> 'ups', '[]') || ups),
    created_at = now(), read_at = null;
  return true;
end $$;
revoke execute on function public.grant_xp(text, text, text, int[], text, uuid) from public, anon, authenticated;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'notifications') then
    alter publication supabase_realtime add table public.notifications;
  end if;
end $$;
